site_name: Портфолио Дмитрия М. - Solution Architecture
site_url: https://flatura.github.io/portfolio
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
plugins:
  - search
  - minify:
      minify_html: true
  - include-markdown
  - glightbox
nav:
  - Главная: index.md
  - Флагманский SaaS проект:
      - MyLovelyGarden (ERP): projects/mlg.md
  - Enterprise-опыт:
      - FMCG Supply Chain Optimization: projects/fmcg_planner_forecaster.md
      - Enterprise GIS Platform: projects/enterprise_gis.md
      - HR KPI System (FastMBO): projects/fastmbo.md
  - R&D и Архитектурные стенды:
      - GraphMechanic: projects/graph-mechanic.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flatura