site_name: "Dmitry M. - Portfolio | Architecture & Systems Analysis"
site_url: https://flatura.github.io/portfolio
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
          site_name: "Портфолио Дмитрия М. - Архитектура и системный анализ"
          nav:
            - Главная: index.md
            - Коммерческие проекты:
                - FMCG ML Прогнозатор / Планировщик: projects/fmcg_forecaster_planner.md
                - ГИС Визуализатор корп.данных: projects/gis_bi_1.md
                - ГИС Визуализатор (продукт): projects/gis_bi_2.md
                - FastMBO: projects/fastmbo.md
            - Внутренние инициативы:
                - PolylineMechanic: projects/polyline-mechanic.md
                - ExpendIt: projects/expendit.md
            - Личные проекты:
                - MLG: projects/mlg.md
                - Serverless Transcriber: projects/serverless_transcriber.md
                - GraphMechanic: projects/graph-mechanic.md
  - search
  - minify:
      minify_html: true
  - include-markdown
  - glightbox
nav:
  - Home: index.md
  - Commercial projects:
      - FMCG ML Forecaster / Planner: projects/fmcg_forecaster_planner.md
      - GIS Data Visualization Project: projects/gis_bi_1.md
      - GIS Data Visualization Product: projects/gis_bi_2.md
      - FastMBO: projects/fastmbo.md
  - Internal initiatives:
      - PolylineMechanic: projects/polyline-mechanic.md
      - ExpendIt: projects/expendit.md
  - Personal projects:
      - MLG: projects/mlg.md
      - Serverless Transcriber: projects/serverless_transcriber.md
      - GraphMechanic: projects/graph-mechanic.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flatura