site_name: Портфолио Дмитрия М. - Архитектура и системный анализ
site_url: https://flatura.github.io/portfolio
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
plugins:
  - search
  - minify:
      minify_html: true
  - include-markdown
  - glightbox
nav:
  - Главная: index.md
  - Коммерческие проекты:
      - GIS Data Visualization Product: projects/gis_bi_2.md
      - GIS Data Visualization Project: projects/gis_bi_1.md
      - MLG: projects/mlg.md
      - FastMBO: projects/fastmbo.md
  - Внутренние инициативы:
      - PolylineMechanic: projects/polyline-mechanic.md
      - ExpendIt: projects/expendit.md
      - GramotaGen: projects/gramotagen.md
  - Личные проекты:
      - GraphMechanic: projects/graph-mechanic.md
      - ArchLab: projects/archlab.md
      - TickFlow: projects/tickflow.md
      - MeteoPal: projects/meteopal.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flatura
