site_name: Портфолио Дмитрия М. - Архитектура и системный анализ
site_url: https://flatura.github.io/portfolio
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
plugins:
  - search
  - minify:
      minify_html: true
  - include-markdown
nav:
  - Главная: index.md
  - Проекты:
      - FastMBO: projects/fastmbo.md
      - MLG: projects/mlg.md
      - GraphMechanic: projects/graph-mechanic.md
      - TickFlow: projects/tickflow.md
      - HabitFree: projects/habitfree.md
      - MeteoPal: projects/meteopal.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flatura
