name: Build & Deploy Pages
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocs-include-markdown-plugin
      - run: git submodule add https://github.com/flatura/fastmbo_docs external/fastmbo_docs
      - run: |
         pwd
         ls -la
         ls -la external || true
         ls -la external/fastmbo_docs || true
         ls -la external/fastmbo_docs/docs || true
      - name: Build site
        run: mkdocs build --strict --site-dir ./site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
